spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whisper
    username: admin
    password: admin
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  # Set REST calls context
  data:
    rest:
      base-path: /api

# Set actuator context path
management:
  context-path: /monitor

# SSL settings
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: tomcat
#    key-password: tomcat

# Enable trace log
#trace: true