-- Run this script only ONCE in PROD

DROP TABLE IF EXISTS account;
CREATE TABLE account (
  ID SERIAL,
  USERNAME VARCHAR(60) NOT NULL,
  PASSWORD VARCHAR(60) NOT NULL, -- must be at least 60, since BCrypt algorithm generates a String of length 60
  ENABLED BOOL DEFAULT true,
  CONSTRAINT UC_USERNAME UNIQUE (USERNAME)
);

DROP TABLE IF EXISTS booking;
CREATE TABLE booking (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  AGENCY_NAME VARCHAR(50) DEFAULT NULL,
  AGENCY_REF VARCHAR(50) DEFAULT NULL,
  TL_NAME VARCHAR(50) DEFAULT NULL,
  TL_PHONE VARCHAR(50) DEFAULT NULL,
  GUIDE_NAME VARCHAR(50) DEFAULT NULL,
  GUIDE_PHONE VARCHAR(50) DEFAULT NULL,
  PLACE VARCHAR(150) DEFAULT NULL,
  BOOKING_DATE DATETIME DEFAULT NULL,
  BOOKING_TIME VARCHAR(20) DEFAULT NULL,
  NR_OF_PEOPLE INT DEFAULT NULL,
  STAFF_ID BIGINT(20) DEFAULT NULL,
  NOTES VARCHAR(255) DEFAULT NULL,
  STATUS VARCHAR(50) DEFAULT NULL,
  CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS staff;
CREATE TABLE staff (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FULL_NAME VARCHAR(50) DEFAULT NULL,
  PHONE VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE booking ADD CONSTRAINT fk_staff_id FOREIGN KEY (staff_id) REFERENCES staff(id);